### ISSUE TITLE
site.css 404 not found for published application

### ISSUE THREAD

**Issue by brian-pickens** [TrilonIO/aspnetcore-Vue-starter#132]
Hello,

Line 14 of the webpack.config.js publishes the css as style.css. However the webapp expects site.css. To fix this I had to fix line 14 to publish the .css as site.css.

**Comment by Vaylandt** [comment]
@brian-pickens-web TY!!!

**Comment by MarkPieszak** [comment]
Wow thanks for pointing this one out @brian-pickens-web 	Let me get a fix in for this asap! :)

**Comment by doroudi** [comment]
is there a temporary solution to this issue? I really need it.

**Comment by brian-pickens** [comment]
This issue is actually already fixed.
